
import React from 'react';
import { Commodity, Activity, MarketInsight, TradeNews } from './types';

export const COMMODITIES: Commodity[] = [
  { ticker: 'MAZ', name: 'YELLOW MAIZE', price: 285.99, change: 3.25, history: Array.from({length: 20}, (_, i) => ({ date: i.toString(), value: 270 + Math.random() * 30 })) },
  { ticker: 'RIC', name: 'LONG GRAIN RICE', price: 620.49, change: -1.8, history: Array.from({length: 20}, (_, i) => ({ date: i.toString(), value: 600 + Math.random() * 40 })) },
  { ticker: 'CSW', name: 'CASHEWS', price: 1247.46, change: 5.41, history: Array.from({length: 20}, (_, i) => ({ date: i.toString(), value: 1200 + Math.random() * 100 })) },
  { ticker: 'SOY', name: 'SOYBEANS', price: 440.55, change: 0.69, history: Array.from({length: 20}, (_, i) => ({ date: i.toString(), value: 430 + Math.random() * 20 })) },
  { ticker: 'SES', name: 'SESAME', price: 1850.20, change: 2.1, history: Array.from({length: 20}, (_, i) => ({ date: i.toString(), value: 1800 + Math.random() * 100 })) },
  { ticker: 'AVO', name: 'HASS AVOCADOS', price: 1.25, change: 4.5, history: Array.from({length: 20}, (_, i) => ({ date: i.toString(), value: 1.1 + Math.random() * 0.2 })) },
  { ticker: 'VNL', name: 'VANILLA BEANS', price: 180.00, change: -2.1, history: Array.from({length: 20}, (_, i) => ({ date: i.toString(), value: 170 + Math.random() * 20 })) },
];

export const PRODUCT_CATALOG = [
  {
    id: 'P-001',
    crop: 'Long Grain Rice',
    category: 'Cereal Grains',
    origin: 'Dar es Salaam',
    region: 'Coastal',
    volume: '90 MT',
    price: 600,
    priceUnit: 'USD/MT',
    grade: 'A',
    supplier: 'Verified Supplier',
    image: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?q=80&w=800&auto=format&fit=crop',
    stockPeriod: 'Feb 04 – Feb 28, 2026',
    harvestSeason: 'May – August',
    description: 'Premium long grain rice sourced from the fertile plains near Dar es Salaam. Low moisture content (12%), excellent milling quality.',
    growingRegions: [
      { name: 'Morogoro', price: 580, volume: '12,000 MT', quality: 'Grade A', elevation: '500m' },
      { name: 'Mbeya', price: 595, volume: '8,500 MT', quality: 'Grade A', elevation: '1200m' },
      { name: 'Shinyanga', price: 560, volume: '6,200 MT', quality: 'Grade B+', elevation: '1100m' },
    ],
    seasonality: [
      { month: 'Jan', status: 'Growth' }, { month: 'Feb', status: 'Growth' },
      { month: 'Mar', status: 'Growth' }, { month: 'Apr', status: 'Growth' },
      { month: 'May', status: 'Harvest' }, { month: 'Jun', status: 'Peak Harvest' },
      { month: 'Jul', status: 'Peak Harvest' }, { month: 'Aug', status: 'Harvest' },
      { month: 'Sep', status: 'Drying' }, { month: 'Oct', status: 'Planting' },
      { month: 'Nov', status: 'Growth' }, { month: 'Dec', status: 'Growth' },
    ],
    logistics: {
      portOfExport: 'Dar es Salaam Port',
      transitToDubai: '12-14 days',
      transitToEurope: '22-26 days',
      transitToChina: '28-32 days',
      containerType: '20ft / 40ft FCL',
      minOrder: '25 MT',
    },
    certifications: ['Phytosanitary Certificate', 'Certificate of Origin', 'SGS Quality Report'],
    priceHistory: Array.from({length: 12}, (_, i) => ({ month: ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'][i], price: 560 + Math.random() * 80 })),
  },
  {
    id: 'P-002',
    crop: 'Yellow Maize',
    category: 'Cereal Grains',
    origin: 'Dar es Salaam',
    region: 'Southern Highlands',
    volume: '213 MT',
    price: 280,
    priceUnit: 'USD/MT',
    grade: 'A',
    supplier: 'Verified Supplier',
    image: 'https://images.unsplash.com/photo-1551754655-cd27e38d2076?q=80&w=800&auto=format&fit=crop',
    stockPeriod: 'Feb 04 – Feb 28, 2026',
    harvestSeason: 'April – July',
    description: 'Grade A yellow maize from the Southern Highlands. Aflatoxin < 10ppb, moisture < 13%. Ideal for animal feed and flour milling.',
    growingRegions: [
      { name: 'Mbeya', price: 272, volume: '450,000 MT', quality: 'Grade A', elevation: '1700m' },
      { name: 'Songea', price: 265, volume: '320,000 MT', quality: 'Grade B+', elevation: '1100m' },
      { name: 'Sumbawanga', price: 268, volume: '580,000 MT', quality: 'Grade A', elevation: '1500m' },
      { name: 'Iringa', price: 275, volume: '210,000 MT', quality: 'Grade A', elevation: '1600m' },
    ],
    seasonality: [
      { month: 'Jan', status: 'Planting' }, { month: 'Feb', status: 'Growth' },
      { month: 'Mar', status: 'Growth' }, { month: 'Apr', status: 'Harvesting' },
      { month: 'May', status: 'Peak Supply' }, { month: 'Jun', status: 'Exporting' },
      { month: 'Jul', status: 'Exporting' }, { month: 'Aug', status: 'Supply Depletion' },
      { month: 'Sep', status: 'Tilling' }, { month: 'Oct', status: 'Planting' },
      { month: 'Nov', status: 'Growth' }, { month: 'Dec', status: 'Growth' },
    ],
    logistics: {
      portOfExport: 'Dar es Salaam Port',
      transitToDubai: '12-14 days',
      transitToEurope: '22-26 days',
      transitToChina: '28-32 days',
      containerType: '20ft / 40ft FCL',
      minOrder: '50 MT',
    },
    certifications: ['Phytosanitary Certificate', 'Certificate of Origin', 'Aflatoxin Test Report', 'SGS Inspection'],
    priceHistory: Array.from({length: 12}, (_, i) => ({ month: ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'][i], price: 250 + Math.random() * 60 })),
  },
  {
    id: 'P-003',
    crop: 'Long Grain Rice',
    category: 'Cereal Grains',
    origin: 'Morogoro',
    region: 'Kilombero Valley',
    volume: '78 MT',
    price: 480,
    priceUnit: 'USD/MT',
    grade: 'A',
    supplier: 'Kilombero Agro',
    image: 'https://images.unsplash.com/photo-1536304993881-460e464bb8c4?q=80&w=800&auto=format&fit=crop',
    stockPeriod: 'Feb 04 – Feb 28, 2026',
    harvestSeason: 'June – September',
    description: 'Aromatic long grain rice from the renowned Kilombero Valley. Known for its superior taste and cooking properties.',
    growingRegions: [
      { name: 'Morogoro', price: 480, volume: '15,000 MT', quality: 'Grade A', elevation: '300m' },
      { name: 'Mbeya', price: 495, volume: '9,000 MT', quality: 'Grade A+', elevation: '1200m' },
    ],
    seasonality: [
      { month: 'Jan', status: 'Growth' }, { month: 'Feb', status: 'Growth' },
      { month: 'Mar', status: 'Flowering' }, { month: 'Apr', status: 'Flowering' },
      { month: 'May', status: 'Maturing' }, { month: 'Jun', status: 'Harvest' },
      { month: 'Jul', status: 'Peak Harvest' }, { month: 'Aug', status: 'Harvest' },
      { month: 'Sep', status: 'Drying' }, { month: 'Oct', status: 'Planting' },
      { month: 'Nov', status: 'Growth' }, { month: 'Dec', status: 'Growth' },
    ],
    logistics: {
      portOfExport: 'Dar es Salaam Port',
      transitToDubai: '12-14 days',
      transitToEurope: '22-26 days',
      transitToChina: '28-32 days',
      containerType: '20ft / 40ft FCL',
      minOrder: '25 MT',
    },
    certifications: ['Phytosanitary Certificate', 'Certificate of Origin', 'Quality Analysis Report'],
    priceHistory: Array.from({length: 12}, (_, i) => ({ month: ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'][i], price: 440 + Math.random() * 80 })),
  },
  {
    id: 'P-004',
    crop: 'Groundnuts',
    category: 'Nuts & Oilseeds',
    origin: 'Mwanza',
    region: 'Lake Zone',
    volume: '32 MT',
    price: 1400,
    priceUnit: 'USD/MT',
    grade: 'A',
    supplier: 'Verified Supplier',
    image: 'https://images.unsplash.com/photo-1567892737-75876fa288c2?q=80&w=800&auto=format&fit=crop',
    stockPeriod: 'Jan 26 – Feb 19, 2026',
    harvestSeason: 'March – June',
    description: 'Premium red-skin groundnuts from the Lake Zone. High oil content (45-50%), ideal for processing and direct consumption.',
    growingRegions: [
      { name: 'Mwanza', price: 1400, volume: '8,500 MT', quality: 'Grade A', elevation: '1140m' },
      { name: 'Shinyanga', price: 1350, volume: '12,000 MT', quality: 'Grade A', elevation: '1100m' },
      { name: 'Tabora', price: 1320, volume: '6,800 MT', quality: 'Grade B+', elevation: '1200m' },
    ],
    seasonality: [
      { month: 'Jan', status: 'Growth' }, { month: 'Feb', status: 'Flowering' },
      { month: 'Mar', status: 'Harvest' }, { month: 'Apr', status: 'Peak Harvest' },
      { month: 'May', status: 'Harvest' }, { month: 'Jun', status: 'Drying' },
      { month: 'Jul', status: 'Export Ready' }, { month: 'Aug', status: 'Exporting' },
      { month: 'Sep', status: 'Tilling' }, { month: 'Oct', status: 'Planting' },
      { month: 'Nov', status: 'Growth' }, { month: 'Dec', status: 'Growth' },
    ],
    logistics: {
      portOfExport: 'Dar es Salaam Port',
      transitToDubai: '12-14 days',
      transitToEurope: '22-26 days',
      transitToChina: '28-32 days',
      containerType: '20ft FCL',
      minOrder: '20 MT',
    },
    certifications: ['Phytosanitary Certificate', 'Aflatoxin Test (<10ppb)', 'Certificate of Origin'],
    priceHistory: Array.from({length: 12}, (_, i) => ({ month: ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'][i], price: 1300 + Math.random() * 200 })),
  },
  {
    id: 'P-005',
    crop: 'Cowpeas',
    category: 'Legume Grains',
    origin: 'Mwanza',
    region: 'Lake Zone',
    volume: '54 MT',
    price: 280,
    priceUnit: 'USD/MT',
    grade: 'A',
    supplier: 'Verified Supplier',
    image: 'https://images.unsplash.com/photo-1515543904379-3d757ade72f4?q=80&w=800&auto=format&fit=crop',
    stockPeriod: 'Jan 26 – Feb 20, 2026',
    harvestSeason: 'February – May',
    description: 'Drought-resistant cowpeas from the Lake Zone. High protein content (23-25%), widely used in East African and West African cuisine.',
    growingRegions: [
      { name: 'Mwanza', price: 280, volume: '4,200 MT', quality: 'Grade A', elevation: '1140m' },
      { name: 'Dodoma', price: 265, volume: '6,800 MT', quality: 'Grade A', elevation: '1120m' },
      { name: 'Singida', price: 270, volume: '3,500 MT', quality: 'Grade B+', elevation: '1500m' },
    ],
    seasonality: [
      { month: 'Jan', status: 'Growth' }, { month: 'Feb', status: 'Harvest' },
      { month: 'Mar', status: 'Peak Harvest' }, { month: 'Apr', status: 'Harvest' },
      { month: 'May', status: 'Drying' }, { month: 'Jun', status: 'Export Ready' },
      { month: 'Jul', status: 'Exporting' }, { month: 'Aug', status: 'Low Stock' },
      { month: 'Sep', status: 'Planting' }, { month: 'Oct', status: 'Growth' },
      { month: 'Nov', status: 'Growth' }, { month: 'Dec', status: 'Growth' },
    ],
    logistics: {
      portOfExport: 'Dar es Salaam Port',
      transitToDubai: '12-14 days',
      transitToEurope: '22-26 days',
      transitToChina: '28-32 days',
      containerType: '20ft FCL',
      minOrder: '20 MT',
    },
    certifications: ['Phytosanitary Certificate', 'Certificate of Origin', 'Moisture Test Report'],
    priceHistory: Array.from({length: 12}, (_, i) => ({ month: ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'][i], price: 250 + Math.random() * 60 })),
  },
  {
    id: 'P-006',
    crop: 'Mung Beans',
    category: 'Legume Grains',
    origin: 'Mwanza',
    region: 'Lake Zone',
    volume: '50 MT',
    price: 480,
    priceUnit: 'USD/MT',
    grade: 'A',
    supplier: 'Verified Supplier',
    image: 'https://images.unsplash.com/photo-1612257416648-ee7a6c5b8a3e?q=80&w=800&auto=format&fit=crop',
    stockPeriod: 'Feb 04 – Feb 28, 2026',
    harvestSeason: 'March – June',
    description: 'High-quality green mung beans ideal for sprouting and dal. Popular in Asian markets with strong export demand.',
    growingRegions: [
      { name: 'Mwanza', price: 480, volume: '3,800 MT', quality: 'Grade A', elevation: '1140m' },
      { name: 'Dodoma', price: 460, volume: '5,200 MT', quality: 'Grade A', elevation: '1120m' },
    ],
    seasonality: [
      { month: 'Jan', status: 'Growth' }, { month: 'Feb', status: 'Growth' },
      { month: 'Mar', status: 'Harvest' }, { month: 'Apr', status: 'Peak Harvest' },
      { month: 'May', status: 'Harvest' }, { month: 'Jun', status: 'Drying' },
      { month: 'Jul', status: 'Export Ready' }, { month: 'Aug', status: 'Exporting' },
      { month: 'Sep', status: 'Planting' }, { month: 'Oct', status: 'Growth' },
      { month: 'Nov', status: 'Growth' }, { month: 'Dec', status: 'Growth' },
    ],
    logistics: {
      portOfExport: 'Dar es Salaam Port',
      transitToDubai: '12-14 days',
      transitToEurope: '22-26 days',
      transitToChina: '28-32 days',
      containerType: '20ft FCL',
      minOrder: '20 MT',
    },
    certifications: ['Phytosanitary Certificate', 'Certificate of Origin', 'Quality Analysis Report'],
    priceHistory: Array.from({length: 12}, (_, i) => ({ month: ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'][i], price: 440 + Math.random() * 80 })),
  },
  {
    id: 'P-007',
    crop: 'Irish Potatoes',
    category: 'Root & Tubers',
    origin: 'Kilimanjaro',
    region: 'Northern Highlands',
    volume: '87 Bags',
    price: 16,
    priceUnit: 'USD/Bag',
    grade: 'A',
    supplier: 'Verified Supplier',
    image: 'https://images.unsplash.com/photo-1518977676601-b53f82ber649?q=80&w=800&auto=format&fit=crop',
    stockPeriod: 'Feb 04 – Feb 28, 2026',
    harvestSeason: 'Year-round (peak Jun–Sep)',
    description: 'Fresh Irish potatoes from the volcanic soils of Kilimanjaro. Consistent sizing, low blemish rate, suitable for chips and processing.',
    growingRegions: [
      { name: 'Kilimanjaro', price: 16, volume: '25,000 Bags', quality: 'Grade A', elevation: '1800m' },
      { name: 'Arusha', price: 15, volume: '18,000 Bags', quality: 'Grade A', elevation: '1400m' },
      { name: 'Mbeya', price: 14, volume: '32,000 Bags', quality: 'Grade B+', elevation: '1700m' },
    ],
    seasonality: [
      { month: 'Jan', status: 'Planting' }, { month: 'Feb', status: 'Growth' },
      { month: 'Mar', status: 'Growth' }, { month: 'Apr', status: 'Harvest' },
      { month: 'May', status: 'Harvest' }, { month: 'Jun', status: 'Peak Supply' },
      { month: 'Jul', status: 'Peak Supply' }, { month: 'Aug', status: 'Peak Supply' },
      { month: 'Sep', status: 'Harvest' }, { month: 'Oct', status: 'Planting' },
      { month: 'Nov', status: 'Growth' }, { month: 'Dec', status: 'Growth' },
    ],
    logistics: {
      portOfExport: 'Dar es Salaam Port',
      transitToDubai: '8-10 days (refrigerated)',
      transitToEurope: '18-22 days (refrigerated)',
      transitToChina: '25-30 days (refrigerated)',
      containerType: '40ft Reefer',
      minOrder: '50 Bags',
    },
    certifications: ['Phytosanitary Certificate', 'Certificate of Origin', 'Cold Chain Certificate'],
    priceHistory: Array.from({length: 12}, (_, i) => ({ month: ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'][i], price: 13 + Math.random() * 6 })),
  },
  {
    id: 'P-008',
    crop: 'Yellow Beans',
    category: 'Legume Grains',
    origin: 'Kilimanjaro',
    region: 'Northern Highlands',
    volume: '53 MT',
    price: 72,
    priceUnit: 'USD/MT',
    grade: 'A',
    supplier: 'Verified Supplier',
    image: 'https://images.unsplash.com/photo-1551462147-ff29053bfc14?q=80&w=800&auto=format&fit=crop',
    stockPeriod: 'Feb 04 – Feb 28, 2026',
    harvestSeason: 'April – July',
    description: 'Nutritious yellow beans from the volcanic soils of Northern Tanzania. High protein content, minimal split rate.',
    growingRegions: [
      { name: 'Kilimanjaro', price: 72, volume: '4,500 MT', quality: 'Grade A', elevation: '1800m' },
      { name: 'Arusha', price: 68, volume: '6,200 MT', quality: 'Grade A', elevation: '1400m' },
    ],
    seasonality: [
      { month: 'Jan', status: 'Growth' }, { month: 'Feb', status: 'Flowering' },
      { month: 'Mar', status: 'Flowering' }, { month: 'Apr', status: 'Harvest' },
      { month: 'May', status: 'Peak Harvest' }, { month: 'Jun', status: 'Harvest' },
      { month: 'Jul', status: 'Drying' }, { month: 'Aug', status: 'Export Ready' },
      { month: 'Sep', status: 'Planting' }, { month: 'Oct', status: 'Growth' },
      { month: 'Nov', status: 'Growth' }, { month: 'Dec', status: 'Growth' },
    ],
    logistics: {
      portOfExport: 'Dar es Salaam Port',
      transitToDubai: '12-14 days',
      transitToEurope: '22-26 days',
      transitToChina: '28-32 days',
      containerType: '20ft FCL',
      minOrder: '20 MT',
    },
    certifications: ['Phytosanitary Certificate', 'Certificate of Origin', 'Quality Analysis Report'],
    priceHistory: Array.from({length: 12}, (_, i) => ({ month: ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'][i], price: 60 + Math.random() * 25 })),
  },
  {
    id: 'P-009',
    crop: 'White Maize',
    category: 'Cereal Grains',
    origin: 'Kilimanjaro',
    region: 'Northern Highlands',
    volume: '43 MT',
    price: 280,
    priceUnit: 'USD/MT',
    grade: 'A',
    supplier: 'Verified Supplier',
    image: 'https://images.unsplash.com/photo-1625246333195-78d9c38ad449?q=80&w=800&auto=format&fit=crop',
    stockPeriod: 'Jan 27 – Feb 27, 2026',
    harvestSeason: 'April – July',
    description: 'Premium white maize for flour milling. Grown in the fertile volcanic soils of Kilimanjaro region.',
    growingRegions: [
      { name: 'Kilimanjaro', price: 280, volume: '15,000 MT', quality: 'Grade A', elevation: '1800m' },
      { name: 'Arusha', price: 275, volume: '22,000 MT', quality: 'Grade A', elevation: '1400m' },
    ],
    seasonality: [
      { month: 'Jan', status: 'Planting' }, { month: 'Feb', status: 'Growth' },
      { month: 'Mar', status: 'Growth' }, { month: 'Apr', status: 'Harvest' },
      { month: 'May', status: 'Peak Supply' }, { month: 'Jun', status: 'Exporting' },
      { month: 'Jul', status: 'Exporting' }, { month: 'Aug', status: 'Low Stock' },
      { month: 'Sep', status: 'Tilling' }, { month: 'Oct', status: 'Planting' },
      { month: 'Nov', status: 'Growth' }, { month: 'Dec', status: 'Growth' },
    ],
    logistics: {
      portOfExport: 'Dar es Salaam Port',
      transitToDubai: '12-14 days',
      transitToEurope: '22-26 days',
      transitToChina: '28-32 days',
      containerType: '20ft / 40ft FCL',
      minOrder: '25 MT',
    },
    certifications: ['Phytosanitary Certificate', 'Certificate of Origin', 'Moisture Test Report'],
    priceHistory: Array.from({length: 12}, (_, i) => ({ month: ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'][i], price: 250 + Math.random() * 60 })),
  },
  {
    id: 'P-010',
    crop: 'Green Peas',
    category: 'Legume Grains',
    origin: 'Kilimanjaro',
    region: 'Northern Highlands',
    volume: '87 Kg',
    price: 0.60,
    priceUnit: 'USD/Kg',
    grade: 'A',
    supplier: 'Verified Supplier',
    image: 'https://images.unsplash.com/photo-1587735243615-c03f25aaff15?q=80&w=800&auto=format&fit=crop',
    stockPeriod: 'Feb 04 – Feb 28, 2026',
    harvestSeason: 'March – June',
    description: 'Fresh green peas from the cool highlands of Kilimanjaro. Sweet flavor, vibrant color, ideal for fresh and frozen markets.',
    growingRegions: [
      { name: 'Kilimanjaro', price: 0.60, volume: '2,500 Kg', quality: 'Grade A', elevation: '1800m' },
      { name: 'Arusha', price: 0.55, volume: '4,000 Kg', quality: 'Grade A', elevation: '1400m' },
    ],
    seasonality: [
      { month: 'Jan', status: 'Planting' }, { month: 'Feb', status: 'Growth' },
      { month: 'Mar', status: 'Harvest' }, { month: 'Apr', status: 'Peak Harvest' },
      { month: 'May', status: 'Harvest' }, { month: 'Jun', status: 'End Season' },
      { month: 'Jul', status: 'Off Season' }, { month: 'Aug', status: 'Off Season' },
      { month: 'Sep', status: 'Planting' }, { month: 'Oct', status: 'Growth' },
      { month: 'Nov', status: 'Growth' }, { month: 'Dec', status: 'Planting' },
    ],
    logistics: {
      portOfExport: 'Dar es Salaam Port',
      transitToDubai: '8-10 days (refrigerated)',
      transitToEurope: '18-22 days (refrigerated)',
      transitToChina: '25-30 days (refrigerated)',
      containerType: '40ft Reefer',
      minOrder: '500 Kg',
    },
    certifications: ['Phytosanitary Certificate', 'Certificate of Origin', 'Cold Chain Certificate'],
    priceHistory: Array.from({length: 12}, (_, i) => ({ month: ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'][i], price: 0.45 + Math.random() * 0.3 })),
  },
  {
    id: 'P-011',
    crop: 'Carrots',
    category: 'Root & Tubers',
    origin: 'Kilimanjaro',
    region: 'Northern Highlands',
    volume: '90 Bags',
    price: 16,
    priceUnit: 'USD/Bag',
    grade: 'A',
    supplier: 'Verified Supplier',
    image: 'https://images.unsplash.com/photo-1598170845058-32b9d6a5da37?q=80&w=800&auto=format&fit=crop',
    stockPeriod: 'Feb 04 – Feb 28, 2026',
    harvestSeason: 'Year-round',
    description: 'Fresh orange carrots from the volcanic soils of Kilimanjaro. Consistent sizing, vibrant color, minimal defect rate.',
    growingRegions: [
      { name: 'Kilimanjaro', price: 16, volume: '15,000 Bags', quality: 'Grade A', elevation: '1800m' },
      { name: 'Arusha', price: 14, volume: '12,000 Bags', quality: 'Grade A', elevation: '1400m' },
    ],
    seasonality: [
      { month: 'Jan', status: 'Available' }, { month: 'Feb', status: 'Available' },
      { month: 'Mar', status: 'Peak Supply' }, { month: 'Apr', status: 'Peak Supply' },
      { month: 'May', status: 'Available' }, { month: 'Jun', status: 'Available' },
      { month: 'Jul', status: 'Available' }, { month: 'Aug', status: 'Peak Supply' },
      { month: 'Sep', status: 'Peak Supply' }, { month: 'Oct', status: 'Available' },
      { month: 'Nov', status: 'Available' }, { month: 'Dec', status: 'Available' },
    ],
    logistics: {
      portOfExport: 'Dar es Salaam Port',
      transitToDubai: '8-10 days (refrigerated)',
      transitToEurope: '18-22 days (refrigerated)',
      transitToChina: '25-30 days (refrigerated)',
      containerType: '40ft Reefer',
      minOrder: '50 Bags',
    },
    certifications: ['Phytosanitary Certificate', 'Certificate of Origin', 'Cold Chain Certificate'],
    priceHistory: Array.from({length: 12}, (_, i) => ({ month: ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'][i], price: 13 + Math.random() * 6 })),
  },
  {
    id: 'P-012',
    crop: 'Cashew Nuts',
    category: 'Nuts & Oilseeds',
    origin: 'Mtwara',
    region: 'Southern Coast',
    volume: '120 MT',
    price: 1240,
    priceUnit: 'USD/MT',
    grade: 'A',
    supplier: 'Coastal Exports',
    image: 'https://images.unsplash.com/photo-1596464716127-f2a82984de30?q=80&w=800&auto=format&fit=crop',
    stockPeriod: 'Feb 01 – Mar 15, 2026',
    harvestSeason: 'October – January',
    description: 'Premium raw cashew nuts (RCN) from the Southern Coast. Tanzania is Africa\'s 3rd largest producer with world-renowned quality.',
    growingRegions: [
      { name: 'Mtwara', price: 1240, volume: '85,000 MT', quality: 'Grade A', elevation: '100m' },
      { name: 'Lindi', price: 1220, volume: '62,000 MT', quality: 'Grade A', elevation: '200m' },
      { name: 'Pwani', price: 1200, volume: '28,000 MT', quality: 'Grade B+', elevation: '50m' },
    ],
    seasonality: [
      { month: 'Jan', status: 'Harvest End' }, { month: 'Feb', status: 'Export Season' },
      { month: 'Mar', status: 'Peak Export' }, { month: 'Apr', status: 'Exporting' },
      { month: 'May', status: 'Low Stock' }, { month: 'Jun', status: 'Off Season' },
      { month: 'Jul', status: 'Flowering' }, { month: 'Aug', status: 'Fruit Setting' },
      { month: 'Sep', status: 'Maturing' }, { month: 'Oct', status: 'Harvest Begins' },
      { month: 'Nov', status: 'Peak Harvest' }, { month: 'Dec', status: 'Harvest' },
    ],
    logistics: {
      portOfExport: 'Mtwara Port / Dar es Salaam',
      transitToDubai: '10-12 days',
      transitToEurope: '20-24 days',
      transitToChina: '22-28 days',
      containerType: '20ft / 40ft FCL',
      minOrder: '25 MT',
    },
    certifications: ['Phytosanitary Certificate', 'Certificate of Origin', 'SGS Quality Report', 'Moisture & KOR Test'],
    priceHistory: Array.from({length: 12}, (_, i) => ({ month: ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'][i], price: 1100 + Math.random() * 300 })),
  },
];

// Legacy fallback for useListings
export const LISTINGS = PRODUCT_CATALOG.map(p => ({
  id: p.id,
  crop: p.crop.toUpperCase(),
  origin: p.origin,
  volume: p.volume,
  price: p.price,
  grade: p.grade,
  supplier: p.supplier,
}));

export const REGIONS = ['ALL REGIONS', 'MBEYA', 'MOROGORO', 'IRINGA', 'MTWARA', 'ARUSHA', 'MANYARA', 'NJOMBE', 'KAGERA', 'KILIMANJARO', 'MWANZA', 'DAR ES SALAAM', 'DODOMA'];

export const INITIAL_ACTIVITIES: Activity[] = [
  { id: '1', type: 'purchase', timestamp: '2 min ago', message: 'Buyer from UAE purchased 150 MT Yellow Maize', details: '$285/MT • Supplier: Mazaohub (Mbeya)' },
  { id: '2', type: 'rfq', timestamp: '8 min ago', message: 'Buyer from India requested quote: 200 MT Sesame', details: 'Destination: Mumbai • 3 suppliers responded' },
  { id: '3', type: 'purchase', timestamp: '12 min ago', message: 'Buyer from Germany purchased 80 MT Cashews', details: '$1,250/MT • Supplier: Kilimanjaro Agro' },
];

export const AI_INSIGHTS: MarketInsight[] = [
  { icon: '💡', title: 'OPPORTUNITY', content: 'Avocado peak harvest begins in 14 days in Njombe. Logistics slots are filling fast.' },
  { icon: '⚠️', title: 'WARNING', content: 'Port congestion in Dar es Salaam increasing. Add 2-3 days to all shipping lead time estimates.' },
];

export const TRADE_NEWS: TradeNews[] = [
  { 
    id: 'n1',
    title: 'Export Ban Lifted: Tanzanian Maize Flow Re-opens', 
    summary: 'The Ministry of Trade has officially terminated the seasonal export ban on Maize.',
    content: 'Policy shift designed to alleviate surplus in the Southern Highlands and capitalize on high demand in GCC markets. Buyers are advised to secure contracts immediately as prices are expected to rise once demand floods in.',
    category: 'POLICY',
    date: 'FEB 18, 2026',
    author: 'GrainX Intel Unit',
    readTime: '4 min',
    image: 'https://images.unsplash.com/photo-1590682680695-43b964a3ae17?q=80&w=800&auto=format&fit=crop'
  },
  { 
    id: 'n2',
    title: 'Cashew Harvest Season: Southern Coast Reports Record Yields', 
    summary: 'Mtwara and Lindi regions report 15% increase in cashew production this season.',
    content: 'Record rainfall and improved farming practices have led to exceptional yields across the Southern Coast. RCN quality metrics are above average with KOR rates exceeding 48lbs. Export-ready stock is expected to peak in March.',
    category: 'MARKET',
    date: 'FEB 15, 2026',
    author: 'GrainX Intel Unit',
    readTime: '3 min',
    image: 'https://images.unsplash.com/photo-1596464716127-f2a82984de30?q=80&w=800&auto=format&fit=crop'
  },
  { 
    id: 'n3',
    title: 'Dar es Salaam Port: New Container Terminal Reduces Wait Times', 
    summary: 'The newly operational terminal has cut average vessel waiting time from 5 days to 2 days.',
    content: 'Infrastructure improvements at Dar es Salaam Port are yielding significant logistical benefits for agricultural exporters. Transit reliability scores have improved across all corridors.',
    category: 'LOGISTICS',
    date: 'FEB 10, 2026',
    author: 'GrainX Intel Unit',
    readTime: '3 min',
    image: 'https://images.unsplash.com/photo-1494412574643-ff11b0a5eb19?q=80&w=800&auto=format&fit=crop'
  },
];

export const EXPORT_GUIDELINES = [
  { country: 'UAE', docs: ['Cert of Origin', 'SGS Quality Insp', 'Phytosanitary Cert'], transit: '12-14 Days' },
  { country: 'Germany', docs: ['Euro 1 Cert', 'Organic Cert', 'Pesticide Res Report', 'SGS'], transit: '22-26 Days' },
  { country: 'China', docs: ['GACC Registration', 'Customs Entry Form', 'Purity Lab Result'], transit: '28-32 Days' },
  { country: 'Ireland', docs: ['Phytosanitary Cert', 'Organic Compliance', 'HACCP Cert'], transit: '24-28 Days' },
];

export const SUPPLY_SIGNALS = [
  { region: 'MBEYA', crop: 'YELLOW MAIZE', signal: 'BULLISH', status: 'HARVEST_SURPLUS' },
  { region: 'MOROGORO', crop: 'LONG GRAIN RICE', signal: 'BEARISH', status: 'LOGISTICS_DELAY' },
  { region: 'LINDI', crop: 'SESAME', signal: 'BULLISH', status: 'GLOBAL_DEMAND' },
  { region: 'NJOMBE', crop: 'HASS AVOCADOS', signal: 'BULLISH', status: 'PEAK_SEASON' },
];

export const CROP_INTEL_EXTENDED: Record<string, any> = {
  'AVOCADOS': {
    name: 'Hass Avocados',
    ticker: 'AVO',
    image: 'https://images.unsplash.com/photo-1523049673857-eb18f1d7b578?q=80&w=800&auto=format&fit=crop',
    description: 'Tanzania is the 3rd largest producer in Africa. Our Hass variety is prized for high oil content (18-22%) and exceptional shelf life.',
    sentiment: 'BULLISH',
    marketCap: '$240M EST',
    lastSale: '$1.25/kg',
    change: '+4.5%',
    regions: [
      { name: 'Njombe', volume: '12,500 MT', price: '$1.25', quality: 'AAA', elevation: '1900m' },
      { name: 'Iringa', volume: '8,400 MT', price: '$1.22', quality: 'AA', elevation: '1600m' },
      { name: 'Mbeya', volume: '15,200 MT', price: '$1.20', quality: 'AAA', elevation: '1750m' }
    ],
    seasonality: [
      { month: 'Jan', status: 'Planting' }, { month: 'Feb', status: 'Growth' }, 
      { month: 'Mar', status: 'Peak Harvest' }, { month: 'Apr', status: 'Peak Harvest' },
      { month: 'May', status: 'Harvesting' }, { month: 'Jun', status: 'End of Season' },
      { month: 'Jul', status: 'Dormant' }, { month: 'Aug', status: 'Dormant' },
      { month: 'Sep', status: 'Pruning' }, { month: 'Oct', status: 'Flowering' },
      { month: 'Nov', status: 'Growth' }, { month: 'Dec', status: 'Growth' }
    ],
    logistics: {
      china: { transit: '28 Days', demand: 'EXTREME', risk: 'LOW' },
      ireland: { transit: '22 Days', demand: 'HIGH', risk: 'MODERATE' }
    }
  },
  'VANILLA': {
    name: 'Planifolia Vanilla',
    ticker: 'VNL',
    image: 'https://images.unsplash.com/photo-1509358271058-acd22cc93898?q=80&w=800&auto=format&fit=crop',
    description: 'Bourbon-style Planifolia beans. Sourced primarily from the humid Kagera region bordering Lake Victoria.',
    sentiment: 'STABLE',
    marketCap: '$45M EST',
    lastSale: '$180.00/kg',
    change: '-1.2%',
    regions: [
      { name: 'Kagera', volume: '45 MT', price: '$180.00', quality: 'PREMIUM', elevation: '1100m' },
      { name: 'Morogoro', volume: '12 MT', price: '$175.00', quality: 'GRADE A', elevation: '900m' }
    ],
    seasonality: [
      { month: 'Jan', status: 'Curing' }, { month: 'Feb', status: 'Curing' }, 
      { month: 'Mar', status: 'Curing' }, { month: 'Apr', status: 'Exporting' },
      { month: 'May', status: 'Exporting' }, { month: 'Jun', status: 'Exporting' },
      { month: 'Jul', status: 'Pollination' }, { month: 'Aug', status: 'Growth' },
      { month: 'Sep', status: 'Growth' }, { month: 'Oct', status: 'Growth' },
      { month: 'Nov', status: 'Growth' }, { month: 'Dec', status: 'Curing' }
    ],
    logistics: {
      china: { transit: '32 Days', demand: 'HIGH', risk: 'LOW' },
      ireland: { transit: '25 Days', demand: 'PREMIUM', risk: 'LOW' }
    }
  },
  'MAIZE': {
    name: 'Yellow Maize',
    ticker: 'MAZ',
    image: 'https://images.unsplash.com/photo-1551733938-466a992c3677?q=80&w=800&auto=format&fit=crop',
    description: 'The staple commodity of East Africa. Tanzania produces 6M+ MT annually, with major surpluses in the Southern Highlands.',
    sentiment: 'BEARISH',
    marketCap: '$1.8B EST',
    lastSale: '$285.99/MT',
    change: '+3.2%',
    regions: [
      { name: 'Mbeya', volume: '450,000 MT', price: '$272', quality: 'GRADE A', elevation: '1700m' },
      { name: 'Songea', volume: '320,000 MT', price: '$265', quality: 'GRADE B+', elevation: '1100m' },
      { name: 'Sumbawanga', volume: '580,000 MT', price: '$268', quality: 'GRADE A', elevation: '1500m' }
    ],
    seasonality: [
      { month: 'Jan', status: 'Planting' }, { month: 'Feb', status: 'Growth' }, 
      { month: 'Mar', status: 'Growth' }, { month: 'Apr', status: 'Harvesting' },
      { month: 'May', status: 'Peak Supply' }, { month: 'Jun', status: 'Exporting' },
      { month: 'Jul', status: 'Exporting' }, { month: 'Aug', status: 'Supply Depletion' },
      { month: 'Sep', status: 'Tilling' }, { month: 'Oct', status: 'Planting' },
      { month: 'Nov', status: 'Growth' }, { month: 'Dec', status: 'Growth' }
    ],
    logistics: {
      china: { transit: '30 Days', demand: 'STABLE', risk: 'LOW' },
      ireland: { transit: '24 Days', demand: 'MODERATE', risk: 'LOW' }
    }
  }
};
