// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://taednaetvicnpyjfplub.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRhZWRuYWV0dmljbnB5amZwbHViIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzEyNDA2MzksImV4cCI6MjA4NjgxNjYzOX0._RrLgKtIN4vA0lptrsk4f2ZPoajKyLU_TgwQ4qNMSF4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});